const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    UPDATE_USER_INFO: 'UPDATE_USER_INFO',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    FETCH_ALLCODE_GENDER_START: 'FETCH_ALLCODE_GENDER_START',
    FETCH_ALLCODE_GENDER_SUCCESS: 'FETCH_ALLCODE_GENDER_SUCCESS',
    FETCH_ALLCODE_GENDER_FAILED: 'FETCH_ALLCODE_GENDER_FAILED',

    FETCH_ALLCODE_ROLE_START: 'FETCH_ALLCODE_ROLE_START',
    FETCH_ALLCODE_ROLE_SUCCESS: 'FETCH_ALLCODE_ROLE_SUCCESS',
    FETCH_ALLCODE_ROLE_FAILED: 'FETCH_ALLCODE_ROLE_FAILED',

    FETCH_ALLCODE_CATEGORY_START: 'FETCH_ALLCODE_CATEGORY_START',
    FETCH_ALLCODE_CATEGORY_SUCCESS: 'FETCH_ALLCODE_CATEGORY_SUCCESS',
    FETCH_ALLCODE_CATEGORY_FAILED: 'FETCH_ALLCODE_CATEGORY_FAILED',

    FETCH_ALLCODE_BRAND_START: 'FETCH_ALLCODE_BRAND_START',
    FETCH_ALLCODE_BRAND_SUCCESS: 'FETCH_ALLCODE_BRAND_SUCCESS',
    FETCH_ALLCODE_BRAND_FAILED: 'FETCH_ALLCODE_BRAND_FAILED',

    FETCH_ALLCODE_WARRANTY_START: 'FETCH_ALLCODE_WARRANTY_START',
    FETCH_ALLCODE_WARRANTY_SUCCESS: 'FETCH_ALLCODE_WARRANTY_SUCCESS',
    FETCH_ALLCODE_WARRANTY_FAILED: 'FETCH_ALLCODE_WARRANTY_FAILED',

    FETCH_ALLCODE_SUBJECT_START: 'FETCH_ALLCODE_SUBJECT_START',
    FETCH_ALLCODE_SUBJECT_SUCCESS: 'FETCH_ALLCODE_SUBJECT_SUCCESS',
    FETCH_ALLCODE_SUBJECT_FAILED: 'FETCH_ALLCODE_SUBJECT_FAILED',

    FETCH_ALLCODE_DISCOUNT_START: 'FETCH_ALLCODE_DISCOUNT_START',
    FETCH_ALLCODE_DISCOUNT_SUCCESS: 'FETCH_ALLCODE_DISCOUNT_SUCCESS',
    FETCH_ALLCODE_DISCOUNT_FAILED: 'FETCH_ALLCODE_DISCOUNT_FAILED',

    FETCH_ALLCODE_AGE_USE_PRODUCT_START: 'FETCH_ALLCODE_AGE_USE_PRODUCT_START',
    FETCH_ALLCODE_AGE_USE_PRODUCT_SUCCESS: 'FETCH_ALLCODE_AGE_USE_PRODUCT_SUCCESS',
    FETCH_ALLCODE_AGE_USE_PRODUCT_FAILED: 'FETCH_ALLCODE_AGE_USE_PRODUCT_FAILED',

    FETCH_ALLCODE_STATUS_ORDER_START: 'FETCH_ALLCODE_STATUS_ORDER_START',
    FETCH_ALLCODE_STATUS_ORDER_SUCCESS: 'FETCH_ALLCODE_STATUS_ORDER_SUCCESS',
    FETCH_ALLCODE_STATUS_ORDER_FAILED: 'FETCH_ALLCODE_STATUS_ORDER_FAILED',

    CREATE_USER_START: 'CREATE_USER_START',
    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    DELETE_USER_START: 'DELETE_USER_START',
    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    EDIT_USER_START: 'EDIT_USER_START',
    EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
    EDIT_USER_FAILED: 'EDIT_USER_FAILED',

    FETCH_ALL_USER_START: 'FETCH_ALL_USER_START',
    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAILED: 'FETCH_ALL_USER_FAILED',

    FETCH_DETAIL_USER_BY_ID_START: 'FETCH_DETAIL_USER_BY_ID_START',
    FETCH_DETAIL_USER_BY_ID_SUCCESS: 'FETCH_DETAIL_USER_BY_ID_SUCCESS',
    FETCH_DETAIL_USER_BY_ID_FAILED: 'FETCH_DETAIL_USER_BY_ID_FAILED',

    FETCH_ALL_PRODUCT_START: 'FETCH_ALL_PRODUCT_START',
    FETCH_ALL_PRODUCT_SUCCESS: 'FETCH_ALL_PRODUCT_SUCCESS',
    FETCH_ALL_PRODUCT_FAILED: 'FETCH_ALL_PRODUCT_FAILED',

    FETCH_TOP_PRODUCT_START: 'FETCH_TOP_PRODUCT_START',
    FETCH_TOP_PRODUCT_SUCCESS: 'FETCH_TOP_PRODUCT_SUCCESS',
    FETCH_TOP_PRODUCT_FAILED: 'FETCH_TOP_PRODUCT_FAILED',

    FETCH_NEW_PRODUCT_START: 'FETCH_NEW_PRODUCT_START',
    FETCH_NEW_PRODUCT_SUCCESS: 'FETCH_NEW_PRODUCT_SUCCESS',
    FETCH_NEW_PRODUCT_FAILED: 'FETCH_NEW_PRODUCT_FAILED',

    DELETE_PRODUCT_START: 'DELETE_PRODUCT_START',
    DELETE_PRODUCT_SUCCESS: 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_FAILED: 'DELETE_PRODUCT_FAILED',

    FETCH_ALL_PRODUCT_IMAGE_FORM_PRODUCT_START: 'FETCH_ALL_PRODUCT_IMAGE_FORM_PRODUCT_START',
    FETCH_ALL_PRODUCT_IMAGE_FORM_PRODUCT_SUCCESS: 'FETCH_ALL_PRODUCT_IMAGE_FORM_PRODUCT_SUCCESS',
    FETCH_ALL_PRODUCT_IMAGE_FORM_PRODUCT_FAILED: 'FETCH_ALL_PRODUCT_IMAGE_FORM_PRODUCT_FAILED',

    FETCH_ALL_BANNER_START: 'FETCH_ALL_BANNER_START',
    FETCH_ALL_BANNER_SUCCESS: 'FETCH_ALL_BANNER_SUCCESS',
    FETCH_ALL_BANNER_FAILED: 'FETCH_ALL_BANNER_FAILED',

    FETCH_LIST_BANNER_START: 'FETCH_LIST_BANNER_START',
    FETCH_LIST_BANNER_SUCCESS: 'FETCH_LIST_BANNER_SUCCESS',
    FETCH_LIST_BANNER_FAILED: 'FETCH_LIST_BANNER_FAILED',

    FETCH_ALL_TYPE_SHIP_START: 'FETCH_ALL_TYPE_SHIP_START',
    FETCH_ALL_TYPE_SHIP_SUCCESS: 'FETCH_ALL_TYPE_SHIP_SUCCESS',
    FETCH_ALL_TYPE_SHIP_FAILED: 'FETCH_ALL_TYPE_SHIP_FAILED',

    FETCH_ALL_BLOG_START: 'FETCH_ALL_BLOG_START',
    FETCH_ALL_BLOG_SUCCESS: 'FETCH_ALL_BLOG_SUCCESS',
    FETCH_ALL_BLOG_FAILED: 'FETCH_ALL_BLOG_FAILED',

    FETCH_LIST_BLOG_START: 'FETCH_LIST_BLOG_START',
    FETCH_LIST_BLOG_SUCCESS: 'FETCH_LIST_BLOG_SUCCESS',
    FETCH_LIST_BLOG_FAILED: 'FETCH_LIST_BLOG_FAILED',

    FETCH_ALL_TYPE_VOUCHER_START: 'FETCH_ALL_TYPE_VOUCHER_START',
    FETCH_ALL_TYPE_VOUCHER_SUCCESS: 'FETCH_ALL_TYPE_VOUCHER_SUCCESS',
    FETCH_ALL_TYPE_VOUCHER_FAILED: 'FETCH_ALL_TYPE_VOUCHER_FAILED',

    FETCH_ALL_VOUCHER_START: 'FETCH_ALL_VOUCHER_START',
    FETCH_ALL_VOUCHER_SUCCESS: 'FETCH_ALL_VOUCHER_SUCCESS',
    FETCH_ALL_VOUCHER_FAILED: 'FETCH_ALL_VOUCHER_FAILED',

    FETCH_ALL_VOUCHER_BY_USER_ID_START: 'FETCH_ALL_VOUCHER_BY_USER_ID_START',
    FETCH_ALL_VOUCHER_BY_USER_ID_SUCCESS: 'FETCH_ALL_VOUCHER_BY_USER_ID_SUCCESS',
    FETCH_ALL_VOUCHER_BY_USER_ID_FAILED: 'FETCH_ALL_VOUCHER_BY_USER_ID_FAILED',

    FETCH_ADD_ITEM_CART_START: 'FETCH_ADD_ITEM_CART_START',
    FETCH_ADD_ITEM_CART_SUCCESS: 'FETCH_ADD_ITEM_CART_SUCCESS',
    FETCH_ADD_ITEM_CART_FAILED: 'FETCH_ADD_ITEM_CART_FAILED',

    FETCH_GET_ALL_ITEM_CART_START: 'FETCH_GET_ALL_ITEM_CART_START',
    FETCH_GET_ALL_ITEM_CART_SUCCESS: 'FETCH_GET_ALL_ITEM_CART_SUCCESS',
    FETCH_GET_ALL_ITEM_CART_FAILED: 'FETCH_GET_ALL_ITEM_CART_FAILED',

    FETCH_ALL_RECEIVER_BY_USER_ID_START: 'FETCH_ALL_RECEIVER_BY_USER_ID_START',
    FETCH_ALL_RECEIVER_BY_USER_ID_SUCCESS: 'FETCH_ALL_RECEIVER_BY_USER_ID_SUCCESS',
    FETCH_ALL_RECEIVER_BY_USER_ID_FAILED: 'FETCH_ALL_RECEIVER_BY_USER_ID_FAILED',

    FETCH_ALL_ORDER_BY_USER_ID_START: 'FETCH_ALL_ORDER_BY_USER_ID_START',
    FETCH_ALL_ORDER_BY_USER_ID_SUCCESS: 'FETCH_ALL_ORDER_BY_USER_ID_SUCCESS',
    FETCH_ALL_ORDER_BY_USER_ID_FAILED: 'FETCH_ALL_ORDER_BY_USER_ID_FAILED',

    FETCH_ALL_ORDER_START: 'FETCH_ALL_ORDER_START',
    FETCH_ALL_ORDER_SUCCESS: 'FETCH_ALL_ORDER_SUCCESS',
    FETCH_ALL_ORDER_FAILED: 'FETCH_ALL_ORDER_FAILED',

    FETCH_ORDER_BY_ID_START: 'FETCH_ORDER_BY_ID_START',
    FETCH_ORDER_BY_ID_SUCCESS: 'FETCH_ORDER_BY_ID_SUCCESS',
    FETCH_ORDER_BY_ID_FAILED: 'FETCH_ORDER_BY_ID_FAILED',

    FETCH_ALL_COMMENT_BY_PRODUCT_ID_START: 'FETCH_ALL_COMMENT_BY_PRODUCT_ID_START',
    FETCH_ALL_COMMENT_BY_PRODUCT_ID_SUCCESS: 'FETCH_ALL_COMMENT_BY_PRODUCT_ID_SUCCESS',
    FETCH_ALL_COMMENT_BY_PRODUCT_ID_FAILED: 'FETCH_ALL_COMMENT_BY_PRODUCT_ID_FAILED',

    FETCH_ALL_IMPORT_START: 'FETCH_ALL_IMPORT_START',
    FETCH_ALL_IMPORT_SUCCESS: 'FETCH_ALL_IMPORT_SUCCESS',
    FETCH_ALL_IMPORT_FAILED: 'FETCH_ALL_IMPORT_FAILED',
})

export default actionTypes;